files:
  - source: /app/src/main/res/values/strings.xml
    translation: /app/src/main/res/values-%two_letters_code%/%original_file_name%
    update_option: update_without_changes
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW
        zh-CN: zh-rCN
        pt-PT: pt-rPT
        pt-BR: pt-rBR
  - source: /app/src/fullLinks/play/listings/en-US/full-description.txt
    translation: /app/src/fullLinks/play/listings/%two_letters_code%/%original_file_name%
    #update_option: update_without_changes
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW
        zh-CN: zh-rCN
  - source: /app/src/fullLinks/play/listings/en-US/full-description.txt
    translation: /app/src/lite/play/listings/%two_letters_code%/%original_file_name%
    #update_option: update_without_changes
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW
        zh-CN: zh-rCN
  - source: /app/src/fullLinks/play/listings/en-US/short-description.txt
    translation: /app/src/fullLinks/play/listings/%two_letters_code%/%original_file_name%
    #update_option: update_without_changes
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW
        zh-CN: zh-rCN
  - source: /app/src/fullLinks/play/listings/en-US/short-description.txt
    translation: /app/src/lite/play/listings/%two_letters_code%/%original_file_name%
    #update_option: update_without_changes
    languages_mapping:
      two_letters_code:
        zh-TW: zh-rTW
        zh-CN: zh-rCN